const INTEREST_RATES = new Map();
INTEREST_RATES.set('HOME', 7);
INTEREST_RATES.set('CAR', 8);
INTEREST_RATES.set('PERSONAL', 12);
INTEREST_RATES.set('BUSINESS', 15);

const LOAN_STATUS = {
  DEFAULT: 'default',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
};

const TRANSACTION_TYPES = {
  WITHDRAW_FROM_ATM: 'WITHDRAW_FROM_ATM',
  WITHDRAW_FROM_BANK: 'WITHDRAW_FROM_BANK',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  TRANSFER: 'TRANSFER',
  DEPOSIT: 'DEPOSIT',
  LOAN_INTEREST_ADDED: 'LOAN_INTEREST_ADDED',
  PENALTY_FOR_NRV: 'PENALTY_FOR_NRV',
  INTEREST_EARNED: 'INTEREST_EARNED',
};

const ACCOUNT_TYPES = {
  LOAN: 'LOAN',
  SAVINGS: 'SAVINGS',
  CURRENT: 'CURRENT',
};

const TOTAL_DEPOSIT_RATE_FOR_LOAN = 40 / 100;
const MINIMUM_LOAN_AMOUNT = 500000;
const MINIMUM_CURRENT_OPENING_AMOUNT = 100000;
const MINIMUM_SAVINGS_OPENING_AMOUNT = 10000;
const MINIMUM_AGE_FOR_CURRENT = 18;
const MINIMUM_AGE_FOR_LOAN = 25;

module.exports = {
  ACCOUNT_TYPES,
  TRANSACTION_TYPES,
  TYPES_OF_ACCOUNT: ['SAVINGS', 'CURRENT', 'LOAN'],
  INTEREST_RATES,
  LOAN_STATUS,
  TOTAL_DEPOSIT_RATE_FOR_LOAN,
  MINIMUM_LOAN_AMOUNT,
  MINIMUM_CURRENT_OPENING_AMOUNT,
  MINIMUM_SAVINGS_OPENING_AMOUNT,
  MINIMUM_AGE_FOR_CURRENT,
  MINIMUM_AGE_FOR_LOAN,
};
