const INTEREST_RATES = new Map();
INTEREST_RATES.set('HOME', 7);
INTEREST_RATES.set('CAR', 8);
INTEREST_RATES.set('PERSONAL', 12);
INTEREST_RATES.set('BUSINESS', 15);

const LOAN_STATUS = {
  DEFAULT: 'default',
  ACTIVE: 'active',
  INACTIVE: 'inactive',
};

const TRANSACTION_TYPES = {
  WITHDRAW_FROM_ATM: 'WITHDRAW_FROM_ATM',
  WITHDRAW_FROM_BANK: 'WITHDRAW_FROM_BANK',
  LOAN_REPAYMENT: 'LOAN_REPAYMENT',
  TRANSFER: 'TRANSFER',
  DEPOSIT: 'DEPOSIT',
  LOAN_INTEREST_ADDED: 'LOAN_INTEREST_ADDED',
  PENALTY_FOR_NRV: 'PENALTY_FOR_NRV',
  INTEREST_EARNED: 'INTEREST_EARNED',
};

const ACCOUNT_TYPES = {
  LOAN: 'LOAN',
  SAVINGS: 'SAVINGS',
  CURRENT: 'CURRENT',
};

const TOTAL_DEPOSIT_RATE_FOR_LOAN = 40 / 100;
const MINIMUM_LOAN_AMOUNT = 500000;
const MINIMUM_CURRENT_OPENING_AMOUNT = 100000;
const MINIMUM_SAVINGS_OPENING_AMOUNT = 10000;
const MINIMUM_AGE_FOR_CURRENT = 18;
const MINIMUM_AGE_FOR_LOAN = 25;
const MAXIMUM_TRANSACTION_CHARGE_AMOUNT = 500;
const TRANSACTION_CHARGE_RATE = 0.5;
const MAXIMUM_DAILY_WITHDRAW_AMOUNT = 50000;
const ONE_TIME_WITHDRAW_LIMIT = 20000;
const CURRENT_ACCOUNT_NRV = 500000;
const CURRENT_ACCOUNT_NRV_PENALTY = 500000;
const SAVINGS_ACCOUNT_NRV = 100000;
const SAVINGS_ACCOUNT_NRV_PENALTY = 100000;
const SAVINGS_ACCOUNT_INTEREST_RATE = 6;
const LESS_THAN_3_TRANSACTION_PENALTY = 500;
const TIMES_LOAN_INTEREST_ADDED_ANNUALLY = 2;
const MONTHS_IN_YEAR = 12;

module.exports = {
  ACCOUNT_TYPES,
  TRANSACTION_TYPES,
  TYPES_OF_ACCOUNT: ['SAVINGS', 'CURRENT', 'LOAN'],
  INTEREST_RATES,
  LOAN_STATUS,
  TOTAL_DEPOSIT_RATE_FOR_LOAN,
  MINIMUM_LOAN_AMOUNT,
  MINIMUM_CURRENT_OPENING_AMOUNT,
  MINIMUM_SAVINGS_OPENING_AMOUNT,
  MINIMUM_AGE_FOR_CURRENT,
  MINIMUM_AGE_FOR_LOAN,
  TRANSACTION_CHARGE_RATE,
  MAXIMUM_TRANSACTION_CHARGE_AMOUNT,
  MAXIMUM_DAILY_WITHDRAW_AMOUNT,
  ONE_TIME_WITHDRAW_LIMIT,
  CURRENT_ACCOUNT_NRV,
  CURRENT_ACCOUNT_NRV_PENALTY,
  SAVINGS_ACCOUNT_NRV,
  SAVINGS_ACCOUNT_NRV_PENALTY,
  SAVINGS_ACCOUNT_INTEREST_RATE,
  MONTHS_IN_YEAR,
  LESS_THAN_3_TRANSACTION_PENALTY,
  TIMES_LOAN_INTEREST_ADDED_ANNUALLY,
};
