# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "branchone" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: naveen
          POSTGRES_DB: banksystem_dummy
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: create env file
        run: |
          touch .env
          echo SECRET="AOCNASDMWFOF8789697y79y78t87y7gyf97tc9trc8bt656" >> .env
          echo DATABASE_NAME="banksystem" >> .env
          echo TEST_DATABASE_NAME="banksystem_dummy" >> .env

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      # - name: Install nodejs migrate
      #   run: npm install node-pg-migrate pg

      # - name: migrate database
      #   run: node migrate.js
      #   env:
      #     DBURL: "postgres://postgres:postgres@localhost:5432/banksystem"

      - name: Query database
        run: psql -U postgres -d banksystem_dummy -h localhost -p 5432 -f creation.sql
        env:
          # postgress password is required; alternatively, you can run:
          # `PGPASSWORD=postgres_password psql ...`
          PGPASSWORD: naveen

      - name: Run the mock tests function
        run: npm test
        env:
          DBURL: postgres://postgres:postgres@localhost:5432/banksystem

